# Generated by Django 5.0.6 on 2024-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpost',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
